name = input("Please enter a name: ")
start_city = input("Please enter a start: ")
destination_city = input("Please enter a destination: ")
means_of_transportation = input("Please enter a means of transportation: ")
print(name,"wants to travel from",start_city, "to", destination_city, "by", means_of_transportation)