name = input("Please enter the given name of the student:")
surname = input("Please enter the surname of the student:")
field = input("Please enter the field of study of the student:")
student_tuple = (name, surname, field)
print(student_tuple)